# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Description of what the lane does"
  lane :custom_lane do
    # add actions here: https://docs.fastlane.tools/actions
  end

  desc "development"
	lane :build_dev do |options|
		update_info_plist
		update_code_signing_settings
		
		# 设置版本号（如果环境变量中有指定）
		if ENV['FL_VERSION_NUMBER_VERSION_NUMBER']
			increment_version_number(
				version_number: ENV['FL_VERSION_NUMBER_VERSION_NUMBER']
			)
		end
		
		build_app(
			scheme: "app2",
			workspace: "app2.xcworkspace",
			export_method: "development",
			configuration: "Debug",
			clean: true,
			xcargs: "GCC_PREPROCESSOR_DEFINITIONS='$(inherited) DEBUG=1'",
			export_options: {
				method: "development",
				compileBitcode: false,
				signingStyle: "manual",
				provisioningProfiles: {
					ENV['FL_APP_IDENTIFIER'] || "com.bto.Light" => ENV['FL_PROVISIONING_PROFILE_SPECIFIER']
				}
			}
		)
	end

	desc "release"
	lane :build_release do |options|
		update_info_plist
		update_code_signing_settings
		
		# 设置版本号（如果环境变量中有指定）
		if ENV['FL_VERSION_NUMBER_VERSION_NUMBER']
			increment_version_number(
				version_number: ENV['FL_VERSION_NUMBER_VERSION_NUMBER']
			)
		end
		
		# 设置构建号（如果环境变量中有指定）
		if ENV['FL_BUILD_NUMBER_BUILD_NUMBER']
			increment_build_number(
				build_number: ENV['FL_BUILD_NUMBER_BUILD_NUMBER']
			)
		end
		
		build_app(
			scheme: "app2",
			workspace: "app2.xcworkspace",
			export_method: "app-store",
			configuration: "Release",
			clean: true,
			export_options: {
				method: "app-store",
				compileBitcode: false,
				signingStyle: "manual",
				provisioningProfiles: {
					ENV['FL_APP_IDENTIFIER'] || "com.bto.Light" => ENV['FL_PROVISIONING_PROFILE_SPECIFIER']
				}
			}
		)
	end
	
end
