# ios/fastlane/Fastfile

default_platform :ios

platform :ios do
  desc "Build Debug IPA"
  lane :build_debug do
    # ✅ 不再调用 import_certificates，由 CI 负责
    gym(
      scheme: "app2",
      configuration: "Debug",
      export_method: "development",
      output_directory: "build/export",
      output_name: "app-debug.ipa",
      clean: true,
      silent: false,
      skip_package_manager: true
    )
  end

  desc "Build Release IPA"
  lane :build_release do
    gym(
      scheme: "app2",
      configuration: "Release",
      export_method: "app-store",
      output_directory: "build/export",
      output_name: "app-release.ipa",
      clean: true,
      silent: false,
      skip_package_manager: true
    )
  end
end